### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ghost** [MscrmTools/MsCrmTools.ScriptsFinder#23]
Every time when i try to find script in entities i get following errer. It was working before but spot working on some moment

![image](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/assets/78415437/e3501451-0b2b-4e3f-ad92-77ea6e282f29)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadRibbonCommands(List`1 emds)
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find(List`1 solutions, Boolean loadManagedEntities, Version crmVersion)
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__20_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by MscrmTools** [comment]
I guess you have something that changed in your Ribbon commands. I will review the code to find where a NullReferenceException could occur

**Comment by MscrmTools** [comment]
@mastasmooky-OT Can you test with this version?

[MsCrmTools.ScriptsFinder.zip](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/13298634/MsCrmTools.ScriptsFinder.zip)

**Comment by ghost** [comment]
@MscrmTools thanks for answer. You are right i have a lot of changes in Ribbon. I have tried it and got following error

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadRibbonCommands(List`1 emds)
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find(List`1 solutions, Boolean loadManagedEntities, Version crmVersion)
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__20_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by MscrmTools** [comment]
@mastasmooky-OT so still the same error... crap... I don't see any other place where a NullReferenceException could occur in this  `LoadRibbonCommands`method

**Comment by ghost** [comment]
@MscrmTools is it possible to get information about what command is that and entity name so i can check what is special with this command

**Comment by MscrmTools** [comment]
@mastasmooky-OT This is a special version that will tell which command and show the command definition.

[MsCrmTools.ScriptsFinder.zip](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/13308460/MsCrmTools.ScriptsFinder.zip)

**Comment by ghost** [comment]
@MscrmTools actually it works fine without error (with library that you sent me in last post) :) But when i upgrade to latest version i'm getting error again ...

**Comment by MscrmTools** [comment]
I did not release publicly the fix. 
I will release it to see f it's ok after that
